function requireAll()

  require("src/startup/collisionClasses")
  createCollisionClasses()
  sti = require "libraries/sti"
  require("src/camera")
  require("src/dialogue")
  require("src/player")
  require("src/npcs/npc")
  require("src/npcs/cow")
  require("src/npcs/blankNpc")
  require("src/npcs/companion")
  require("src/enemies/enemy")
  require("src/enemies/glitch1")
  require("src/maps/mapData")
  require("src/maps/maps")
  require("src/maps/farmland2")
  require("src/maps/farmHouse3")
  require("src/items/item")
  require("src/items/heart")
  require("src/items/respawnStone")
  talkies = require("libraries/talkies/talkies")
  require("src/inventory")
  require("libraries.anim8.anim8")
  vector = require("libraries/hump/vector")
  flux = require "libraries/flux/flux"
  require("src/update")
  require("src/draw")
  require("src/phase")
end
